// 9.Print all subsequences of a string
// Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Examples:

// Input : abc
// Output : a, b, c, ab, bc, ac, abc

// Input : aaa
// Output : a, aa, aaa
// solution 1: recursively remove first charecter and for first node add this first character to output and
// for second node just send the output without adding first character of the input

#include <bits/stdc++.h>
using namespace std;
unordered_set<string> s;
void printSeq(string input, string output)
{
    if (input.empty())
    {
        cout << output << " ";
        s.insert(output);
        return;
    }
    printSeq(input.substr(1), output + input[0]);
    printSeq(input.substr(1), output);
}
int main()
{
    string str = "aaa";
    printSeq(str, "");
    cout << endl;
    cout << "distinct subsequence : " << s.size() - 1 << endl;
    return 0;
}